CREATE TABLE `consultants` (
	`run_id` text NOT NULL,
	`slug` text NOT NULL,
	`consultant_name` text,
	`consultant_title_prefix` text,
	`profile_url` text,
	`profile_slug` text NOT NULL,
	`http_status` integer,
	`profile_status` text NOT NULL,
	`registration_number` text,
	`gmc_code_for_booking` text,
	`hospital_name_primary` text,
	`hospital_code_primary` text,
	`has_photo` integer,
	`specialty_primary` text DEFAULT '[]' NOT NULL,
	`specialty_sub` text DEFAULT '[]' NOT NULL,
	`plain_english_score` integer,
	`bio_depth` text,
	`treatments` text DEFAULT '[]' NOT NULL,
	`treatments_excluded` text DEFAULT '[]' NOT NULL,
	`treatment_specificity_score` text,
	`insurers` text DEFAULT '[]' NOT NULL,
	`insurer_count` integer,
	`qualifications_credentials` text,
	`practising_since` integer,
	`memberships` text DEFAULT '[]' NOT NULL,
	`clinical_interests` text DEFAULT '[]' NOT NULL,
	`personal_interests` text,
	`languages` text DEFAULT '[]' NOT NULL,
	`consultation_times_raw` text DEFAULT '[]' NOT NULL,
	`declaration` text,
	`in_the_news` text,
	`professional_roles` text,
	`patient_age_restriction` text,
	`patient_age_restriction_min` integer,
	`patient_age_restriction_max` integer,
	`external_website` text,
	`cqc_rating` text,
	`booking_caveat` text,
	`contact_phone` text,
	`contact_mobile` text,
	`contact_email` text,
	`hospital_is_nuffield` integer,
	`hospital_nuffield_at_nhs` integer,
	`declaration_substantive` integer,
	`booking_state` text,
	`online_bookable` integer,
	`available_slots_next_28_days` integer,
	`next_available_date` text,
	`consultation_price` text,
	`profile_completeness_score` real,
	`quality_tier` text,
	`flags` text DEFAULT '[]' NOT NULL,
	`scrape_status` text NOT NULL,
	`scrape_error` text,
	`manually_reviewed` integer DEFAULT false NOT NULL,
	`reviewed_at` text,
	`reviewed_by` text,
	PRIMARY KEY(`run_id`, `slug`),
	FOREIGN KEY (`run_id`) REFERENCES `scrape_runs`(`run_id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `scrape_runs` (
	`run_id` text PRIMARY KEY NOT NULL,
	`started_at` text NOT NULL,
	`completed_at` text,
	`status` text NOT NULL,
	`total_profiles` integer DEFAULT 0 NOT NULL,
	`success_count` integer DEFAULT 0 NOT NULL,
	`error_count` integer DEFAULT 0 NOT NULL
);
